const mutationsTypes = {
  SET_CHARACTER_LIST: "SET_CHARACTER_LIST",
  SET_FAVOURITES_LIST: "SET_FAVOURITES_LIST",
  SET_TOTAL_NUMBER_OF_PAGES: "SET_TOTAL_NUMBER_OF_PAGES",
  SET_CURRENT_CHARACTER_DETAILS: "SET_CURRENT_CHARACTER_DETAILS",
  ADD_TO_FAVOURITES: "ADD_TO_FAVOURITES",
  IS_LOADING: "IS_LOADING",
};

export default {
  ...mutationsTypes,
};
